export const RESPONSE_TYPE = {
    SUCCESS: "Success",
    ERROR: "Error",
};

export const ERROR_MESSAGE = {
    USER_NOT_EXISTS: "User does not exist",
    INVALID_LOGIN_REQUEST: "Invalid Email or Password",
    INVALID_CAPTCHA: "Invalid Captcha",
    UNAUTHORIZED_REQUEST: "Unauthorized Access",
    INVALID_TOKEN: "Invalid Token",
    INVALID_REQUEST: "Invalid Request",
    ROLE_EXISTS: "Role already exists",
    ROLE_NOT_EXISTS: "Role does not exist",
    USER_EXISTS: "User already exists",    
    INVALID_OLD_PASSWORD: "Invalid old password",
    INTERNAL_SERVER_ERROR: "Internal Server Error",
    ROLE_ASSIGNED_TO_USER: "This role is assigned and cannot be deleted",
    EMAIL_NOT_FOUND: "This email address does not exist",
    INVALID_IMAGE_DATA: "Invalid image data",
    LEAD_NOT_EXISTS: "Lead does not exist",
    FAQ_NOT_EXISTS: "Faq does not exist",
};

export const SUCCESS_MESSAGE = {
    LOGGED_IN: "Logged In",
    PROFILE_UPDATED: "Profile updated successfully",
    ROLES_FETCHED: "Roles fetched successfully",
    ROLE_CREATED: "Role created successfully",
    ROLE_UPDATED: "Role updated successfully",
    ROLE_DELETED: "Role deleted successfully",
    ROLE_FETCHED: "Role fetched successfully",
    PASSWORD_UPDATED: "Password updated successfully",
    METRICS_FETCHED: "Dashboard metrics fetched successfully",
    EMPTY_MESSAGE: "",
    USERS_FETCHED: "Users fetched successfully",
    USER_CREATED: "User created successfully",
    USER_UPDATED: "User updated successfully",
    USER_DELETED: "User moved to trash successfully",
    USER_HARD_DELETED: "User deleted successfully",
    USER_RESTORED: "User restored successfully",
    USER_FETCHED: "User fetched successfully",
    LEAD_CREATED: "Lead created successfully",
    LEAD_UPDATED: "Lead updated successfully",
    LEAD_DELETED: "Lead moved to trash successfully",
    FAQ_CREATED: "Faq created successfully",
    FAQ_UPDATED: "Faq updated successfully",
    FAQ_DELETED: "Faq moved to trash successfully",
};
